name: publish

on: [workflow_dispatch]

jobs:
  publish:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, ubuntu-24.04]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      with: { fetch-depth: 0 }
    - run: git fetch --force --tags

    - name: Install dependencies (Ubuntu)
      if: contains(matrix.platform, 'ubuntu')
      run: |
        sudo apt-get update && sudo apt-get upgrade
        sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
    
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@0b1efabc08b657293548b77fb76cc02d26091c7e
      with:
        toolchain: stable

    - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5
      with:
        workspaces: src-tauri
        shared-key: ${{ matrix.platform }}

    - name: Setup node
      uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f
      with:
        node-version: latest

    - name: Install frontend dependencies
      run: pnpm install
    
    - name: Build and upload assets
      uses: tauri-apps/tauri-action@390cbe447412ced1303d35abe75287949e43437a
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
        TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
      with:
        projectPath: app
        tauriScript: pnpm tauri
        uploadWorkflowArtifacts: true
        tagName: v__VERSION__
        releaseName: 'v__VERSION__'
        releaseAssetNamePattern: '[name]-[version]_[platform]-[arch][ext]'
        releaseDraft: true
